install android-sdk
install ansible
install bazaar
install caskroom/cask/brew-cask
install curl
install fish
install gettext
install git
install git-flow-avh
install gnu-getopt
install go
install httpie
install lua
install mercurial
install rcm
install tmux
install macvim
install boot2docker
install fig
