install caskroom/cask/brew-cask
tap thoughtbot/formulae
install curl
install fish
install gettext
install git
install git-flow-avh
install gnu-getopt
install go
install httpie
install lua
install rcm
install tmux
install the_silver_searcher
cask Caskfile
